### PR TITLE
Added necessary .gitgnore file

### PR DESCRIPTION
**Pull request by Zildj1an**
Request autogenerated with github.com/Zildj1an/ignores

### CODE REVIEW

**Comment by evanphx** [comment]
What?

**Comment by Zildj1an** [comment]
It's the git-ignore file for your C source code, what's the matter?

**Comment by Zildj1an** [comment]
Oh I see now that this is a Ruby project. For some reason GitHub thinks this is C and my script sent this

**Comment by evanphx** [comment]
It's 10 years old. Are you just sending gitignore PRs to a whole bunch of projects?

**Comment by Zildj1an** [comment]
Yes

**Comment by evanphx** [comment]
... why?

**Comment by Zildj1an** [comment]
why not? I literally do no work, it's an automated script that uses the GitHub API. Some projects could benefit from the .gitignore file. A lot of new users don't even know about the feature.

**Comment by Zildj1an** [comment]
It's a silly script github.com/Zildj1an/ignores

**Pull request closed without merging**
